version: "3.8"

services:
  snapfilething:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Web Interface + API
      - "8081:8081" # Static files
    volumes:
      - ./uploads:/app/uploads
    environment:
      - RUST_LOG=info
    env_file:
      - backend/.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
    driver: local
